### ISSUE TITLE
TMP-1(a) Create Add/View/Edit/Delete Functionality for Institute

### ISSUE THREAD

**Issue by RahulSawale** [Prasad108/TutesMessanger#10]
#9 

Hi @Prasad108  Please Check this issue.

**Comment by Prasad108** [comment]
functionality of creat, view and edit has been added 
check on [ http://tutem-tutesmessanger.7e14.starter-us-west-2.openshiftapps.com ](url)

@RahulSawale @snehalslokhande @gopalparihar93
