### ISSUE TITLE
TMP-2 Create "Institute Structure"

### ISSUE THREAD

**Issue by RahulSawale** [Prasad108/TutesMessanger#11]
Hi @AbhishekPatwaCSE 

Please Check this issue.

## Action Items
* Add 'Institute Structure'  in Side Navigation/Menu Bar of Admin Page, page should have like this.
  * Institute Structure
    * Add Branch
    * Add Class
    * Add Division

ask @Prasad108 for details.
Thanks.

**Comment by Prasad108** [comment]
hi all ,
I have created functionality to
 1. add branch,
2. class and 
3. division to the institute 
4. functionality to check the institute structure in tree format 

u can go through it and check it , feel free to give feedback
[http://tutesmessanger-testjavwithdb.7e14.starter-us-west-2.openshiftapps.com/gologin](url)

username-Admin
password-Admin

- add new institute with its admin 
- Login with username as Emailid of Admin and password as contact no of Admin

check 
1. Inst structure with its 2 functionalities and 
2. profile- change password functionlaity created by @aru21 

tag 
@RahulSawale , @AbhishekPatwaCSE  , @lkapure123 , @gopalparihar93 , @AnilNalawade @marutijogdand007 , @aru21

**Comment by Prasad108** [comment]
created the functionality with GUI
