### ISSUE TITLE
Change Password and Edit Profile for teacher

### ISSUE THREAD

**Issue by Prasad108** [Prasad108/TutesMessanger#16]
To @aru21 , @AnilNalawade 

- After Master Admin registers the institute he will assign some simple username and password to Institute Admin  

- After logging in with the default username and password given by Master Admin, Institute Admin will have to change his credentials and should edit his profile 

Criteria For New Username and Password
1. Username
    1. It must be unique.
    2. Capital alphabet (A-Z)(at least one)
    3. Small alphabet (a-z)(at least one)
    3. It's Length must be greater than 5 character.
    4. It's length must be less than 15 character. 
    5. It should be case Sensitive 

2. Password 
   1. It's Length must be greater than 5 character.
   2. It's length must be less than 15 character. 
   3. Numeric figure (at least one)
   4. Capital alphabet (A-Z)(at least one)
   5. Small alphabet (a-z)(at least one)
   6. Special character (#, $, %, &amp;, etc.) (at least one)

- Do research on what should be in profile of teacher - @aru21 , @gopalparihar93 

- _use form elements from template, so that it will responsive on all resolutions_

 tagging
@prasad108 , @RahulSawale

**Comment by RahulSawale** [comment]
Hi all,
Please refer following flow of this.

1) Mater Admin(while institute creation)
  - 'Master Admin' contains Basic Information of Institute.
2) Institute Admin(while 'Master Admin' creation)
  - 'Institute Admin' contains all permission, he has to add/edit/delete/view functionality of every module.


let me know if any suggestion or query 
thanks

@Prasad108 , @AnilNalawade , @aru21 , @gopalparihar93

**Comment by aru21** [comment]
Change Password Functionality
Changes in
       - TeacherController
       -All service and Dao layer of teacher (new methods are added)
       -change in jsp page of teacherMenu.jsp
       -add new jsp page of changePassword.jsp
