### ISSUE TITLE
make Field Not Null Because they take null value.

### ISSUE THREAD

**Issue by AbhishekPatwaCSE** [Prasad108/TutesMessanger#17]
@Prasad108  Please check on Add Institue Page. Its is accepting null value please Make the field Required.

**Comment by Prasad108** [comment]
solved the problem by adding required attribute also applied length=50 attribute 

![issuisloved](https://user-images.githubusercontent.com/28777757/28810368-0edf5b6e-76a7-11e7-892b-17b4e71fc27c.JPG)
