### ISSUE TITLE
Use code for the edit the data table row

### ISSUE THREAD

**Issue by gopalparihar93** [Prasad108/TutesMessanger#18]
![img_20170220_131155 1](https://user-images.githubusercontent.com/26159212/28796883-df737134-765c-11e7-8113-0cf40d209120.jpg)
![img_20170220_131155 2](https://user-images.githubusercontent.com/26159212/28796884-df7be616-765c-11e7-81e3-e217275689f2.jpg)

**Comment by RahulSawale** [comment]
Great, Keep Searching..
@gopalparihar93 please make sure that tag everyone in every comments.
