### ISSUE TITLE
request mapping error cannot map "Admin/GoToAddInstitute"

### ISSUE THREAD

**Issue by Prasad108** [Prasad108/TutesMessanger#2]
1>not able to map the request "Admin/GoToAddInstitute" 
2> we get the containt of page but CSS and jquery not getting applied

![issue1](https://user-images.githubusercontent.com/28777757/28451347-5a268a5c-6e0a-11e7-924f-b177cc910543.jpg)

**Comment by RahulSawale** [comment]
Hi @Prasad108,

you should add Request Mapping on Controller.
PFB

```
@RequestMapping("/Admin")
public class AppAdminController {
@RequestMapping("/GoToAddInstitute")

}
```

please refer [http://milanov.github.io/2015/10/13/routing-options-in-spring-mvc.html](url)

**Comment by Prasad108** [comment]
Hi @RahulSawale  thanks for nice suggestion
    however it is not working, url is getting mapped but bootstrap and css is not getting applied
link u sent is helpful

**Comment by RahulSawale** [comment]
hi @Prasad108  is this issue resolved?

if not then we need to keep all controller entries in 'dispacher' file. mapped with ModelAndView Methods.

**Comment by Prasad108** [comment]
hi @RahulSawale 
## can u share some sample code ?

**Comment by Prasad108** [comment]
Hi all,
Finally this **bug is fixed** 

the problem was with the that while referring to CSS and JS we have to search in the root folder not in the mapped URL by controller adding "/TutesMessanger/" at the beginning.

also we started adding angular into it

![bugfixed](https://user-images.githubusercontent.com/28777757/31227339-1f2a712e-a9f7-11e7-8eab-9fcb0ab3b0d1.jpg)


**solution**

![solution](https://user-images.githubusercontent.com/28777757/31227778-c43ef422-a9f8-11e7-862f-2d2c9d82b8a5.png)



tags:
@RahulSawale @aru21 @snehalslokhande
