### ISSUE TITLE
create Home page for the teacher

### ISSUE THREAD

**Issue by Prasad108** [Prasad108/TutesMessanger#39]
it should show all the icons for all the main links in the application.
ie. user should be able to go to important links without having need to go to  menu

**Comment by RahulSawale** [comment]
Hi @AnilNalawade  / @Prasad108  - please refer following attachment.
![fees-template](https://user-images.githubusercontent.com/15649415/35184923-bc2eb43e-fe21-11e7-8951-1e532f86d134.png)
 


It should more attractive.
refer all functionality from http://www.krtya.com/products/mytuition.aspx

tagging
@gopalparihar93
