### ISSUE TITLE
create the Menue Bar for the Teacher 

### ISSUE THREAD

**Issue by Prasad108** [Prasad108/TutesMessanger#4]
it should have  following things 
edit the menu of template kept in the file `WEB-INF/jsp/components/defaultMenue.jsp` and save in another jsp page so that we can include it whenever required

1. add branch(ie arts, commerce or E&TC , Comp)
 2. add class (ie 11th , 12 th)
 3. add div (eg div A, div B.. )
 4. see schedule( if possible on the calendar widget of the template)
 5. modify and update schedule 
 6. set exam
 7. update exam result
 8. see, update, modify attendance
 9. ### **send message to -teachers, students , parent**
 10. ###  **send email** to -teacher , student, parent 
 11. see the history of sent messages and mails
 12. add another teacher or student to institute

**Comment by Prasad108** [comment]
created with simple headings 

![teacher menu](https://user-images.githubusercontent.com/28777757/28499177-4da82f28-6f7d-11e7-9394-86ef455e4dd0.PNG)

# plz fill free to give suggestions #

**Comment by RahulSawale** [comment]
Great, Add Sub Menu too.
Nice Work @Prasad108  keep it up.
