### ISSUE TITLE
select subject block is empty when page loads

### ISSUE THREAD

**Issue by Dipaksutar100** [Prasad108/TutesMessanger#49]
Expected: 
It should not be displayed.
Block should be displayed only after exam selection.

![defect1](https://user-images.githubusercontent.com/30189783/36349003-bce24782-14a2-11e8-9661-1f92aa506e80.PNG)

@shubhamvwankhade @Prasad108

**Comment by Prasad108** [comment]
@Dipaksutar100  solved the issue, please check .
