### ISSUE TITLE
Change username

### ISSUE THREAD

**Issue by Prasad108** [Prasad108/TutesMessanger#68]
1. Get input of current user name
2. get input new username 

- apply the walidation 
- at least 1 Capital alphabate
- at least 1 small alphabate
- at leat one speacial char of[@,*$_]
- at least 1 Capital number

check the current username in db
1.  if it is correct then 
- update the new username 
- show the success message to user

else
2. ask user to enter correct current username

**Comment by Prasad108** [comment]
tag @rahulnagure  
check the issue and do it ASPA
for any help please free to contact

**Comment by Prasad108** [comment]
hi @rahulnagure  check changeTUsername method in teacher controller for reference

**Comment by Prasad108** [comment]
Hi @rahulnagure any update on change username or sms module ?

**Comment by Prasad108** [comment]
U can send the data from angular $http to the MVC controller

NOTE: request data shuld be in JSON : eg. {"customerInfo":{"firstname":"xyz","lastname":"XYZ"}}

```
@RequestMapping(value = "/send", headers = "Accept=application/json", method = RequestMethod.POST)
public void sendEmails(@RequestBody HashMap<String, HashMap<String, String>> requestData) {

    HashMap<String, String> customerInfo = requestData.get("customerInfo");
    String firstname = customerInfo.get("firstname");
    String lastname = customerInfo.get("lastname");
    //TODO now do whatever you want to do.
}
```

@AbhishekPatwaCSE 
@rahulnagure

**Comment by Prasad108** [comment]
hi @AbhishekPatwaCSE  
u can get the response of the request in the **request**  object 
u can get the status in  **response.data** is the object u sent from controller
u can get its status like **response.data.status**

- after getting the success response user should be shown success message and form should get cleared
- if there status is failed then u should show the error message to the user


 for success use like this 
```
<div class="alert alert-info fade in" ng-show="ExamCreateSuccess">
                          <button data-dismiss="alert" class="close close-sm" type="button">
                              <i class="icon-remove"></i>
                          </button>
                          <strong>Exam Added Successfully</strong> 
</div>
```

for error
```

<div class="alert alert-block alert-danger fade in "  for="inputSuccess" ng-show="ExamCreateError">
                          <button data-dismiss="alert" class="close close-sm" type="button">
                              <i class="icon-remove"></i>
                          </button>
                        <strong>Error in saving Exam</strong>
                      </div>
```

check for `ng-show` variables u have to change there binary value in order to show or hide

**Comment by AbhishekPatwaCSE** [comment]
Hi @Prasad108 

Teachers are able to Update the username successfully.
Error message is also Display when username is not available in databases or 
current name and username is same.

**Comment by Prasad108** [comment]
Hi @AbhishekPatwaCSE 

Good Work 
You have correctly implemented the RestService in Controller.

however please pay attention to following point 
1. all the validation as mention in this issue (u can see them in issue description)
2. also make the look and feel of the form more better

overall great work, u r learning quickly
