### ISSUE TITLE
Modify Institute Structure

### ISSUE THREAD

**Issue by Prasad108** [Prasad108/TutesMessanger#69]
features should be implemented in Angular js 

it should work as it was working in the JSP 
try to reuse the code by making reusable component 
 keep the code separate and clean (if required make use of directives for each feature)

**Comment by Prasad108** [comment]
hi @AnilNalawade 

for this issue we should use reusable angular directive for the drop down creation (branch, class, div)
if u get the time then please watch the video on pluralsight named **[Angular Js Directives Fundamentals](https://app.pluralsight.com/library/courses/angularjs-directive-fundamentals/table-of-contents)**
credentials are 
username : prasad-dukale
password : Dukale@108

**Comment by Prasad108** [comment]
Hi @AnilNalawade 
the first page should contain the menu for all available modificaion options like
## Menu
### Branch    
 

- Add
- Rename  
- Delete
### Class      
- Add 
-    Rename
-   Delete
### Div           
- Add
- Rename
-  Delete

all this nine pages will be different. our time will be saved if we can create some reusable component for drop down of (Branch, Class, Div)

please share your thoughts on this approach

**Comment by Prasad108** [comment]
#60  is created for this issu

**Comment by Prasad108** [comment]
@AnilNalawade this issue need to be resolved before 27- May 2018

**Comment by Prasad108** [comment]
Hi @AnilNalawade ,

Great work, design is also very nice.
Following are some points where we can improve

1. After adding branch, the input field should get cleared (same for add new class).
2. Change the glimph-icon for modify inst.struct and And for every add ,rename and delete it should show respective icon.
3. Change rename icon from modify institute structure page.
4. For rename branch second lable can be 'New name to branch' (same for other).
5. In Rename feature of all make the validation that: 1) new name and current name is not same. 2) New name is not given in the same (institute ,branch, class ,div).
6. After successful deletion of the class the fields should get reset.

U have made Good and quick progress.

**Comment by Prasad108** [comment]
1.That is easy part, I will do that.
2.Yes, i have changed glimph-icons for modify inst. structure and for every add,rename and delete.
3.already done.
4.That also done .
5.This part remain, I can do that.
6.this is for all branch, class and division.

**Comment by AnilNalawade** [comment]
Hi @Prasad108 ,

I have done whatever validation and changes mentioned in above comment.
Now I am working for validation like,
1.Branch name should not be blank for add and rename functionality, if it is blank then undefined value saved in database.(same for class and division functionality).

**Comment by Prasad108** [comment]
[Dump20180603.txt](https://github.com/Prasad108/TutesMessanger/files/2065860/Dump20180603.txt)

**Comment by Prasad108** [comment]
well done @AnilNalawade  pr
